// <auto-generated />
using System;
using KmyKeiba.Downloader;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KmyKeiba.Downloader.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220507063356_AddPreviousRaceDays")]
    partial class AddPreviousRaceDays
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KmyKeiba.Data.Db.ExactaOddsData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<short>("DataStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("HorseNumber1")
                        .HasColumnType("smallint");

                    b.Property<short>("HorseNumber2")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("Odds")
                        .HasColumnType("smallint");

                    b.Property<string>("RaceKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RaceKey");

                    b.ToTable("ExactaOdds");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.FrameNumberOddsData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<short>("DataStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("Frame1")
                        .HasColumnType("smallint");

                    b.Property<short>("Frame2")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("Odds")
                        .HasColumnType("smallint");

                    b.Property<string>("RaceKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RaceKey");

                    b.ToTable("FrameNumberOdds");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.HorseBloodData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<int>("BornYear")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<short>("Color")
                        .HasColumnType("smallint");

                    b.Property<short>("DataStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("FatherKey")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<short>("From")
                        .HasColumnType("smallint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MotherKey")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("varchar(72)");

                    b.Property<string>("ProductingName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<short>("Sex")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Code");

                    b.ToTable("HorseBloods");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.HorseData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<short>("Belongs")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Born")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<short>("Color")
                        .HasColumnType("smallint");

                    b.Property<short>("DataStatus")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Entried")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FFBreedingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("FFFBreedingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("FFMBreedingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("FMBreedingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("FMFBreedingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("FMMBreedingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("FatherBreedingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("InviteFrom")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MFBreedingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("MFFBreedingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("MFMBreedingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("MMBreedingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("MMFBreedingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("MMMBreedingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("MotherBreedingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("varchar(72)");

                    b.Property<string>("OwnerCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ProducingCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("Retired")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("Sex")
                        .HasColumnType("smallint");

                    b.Property<string>("TrainerCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Code", "FatherBreedingCode", "MotherBreedingCode");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.LearningDataCache", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Cache")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CacheVersion")
                        .HasColumnType("int");

                    b.Property<string>("HorseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RaceKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LearningDataCaches");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.QuinellaOddsData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<short>("DataStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("HorseNumber1")
                        .HasColumnType("smallint");

                    b.Property<short>("HorseNumber2")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("Odds")
                        .HasColumnType("smallint");

                    b.Property<string>("RaceKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RaceKey");

                    b.ToTable("QuinellaOdds");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.QuinellaPlaceOddsData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<short>("DataStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("HorseNumber1")
                        .HasColumnType("smallint");

                    b.Property<short>("HorseNumber2")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("PlaceOddsMax")
                        .HasColumnType("smallint");

                    b.Property<short>("PlaceOddsMin")
                        .HasColumnType("smallint");

                    b.Property<string>("RaceKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RaceKey");

                    b.ToTable("QuinellaPlaceOdds");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.RaceData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<TimeSpan>("Corner1LapTime")
                        .HasColumnType("time(6)");

                    b.Property<short>("Corner1Number")
                        .HasColumnType("smallint");

                    b.Property<short>("Corner1Position")
                        .HasColumnType("smallint");

                    b.Property<string>("Corner1Result")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<TimeSpan>("Corner2LapTime")
                        .HasColumnType("time(6)");

                    b.Property<short>("Corner2Number")
                        .HasColumnType("smallint");

                    b.Property<short>("Corner2Position")
                        .HasColumnType("smallint");

                    b.Property<string>("Corner2Result")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<TimeSpan>("Corner3LapTime")
                        .HasColumnType("time(6)");

                    b.Property<short>("Corner3Number")
                        .HasColumnType("smallint");

                    b.Property<short>("Corner3Position")
                        .HasColumnType("smallint");

                    b.Property<string>("Corner3Result")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<TimeSpan>("Corner4LapTime")
                        .HasColumnType("time(6)");

                    b.Property<short>("Corner4Number")
                        .HasColumnType("smallint");

                    b.Property<short>("Corner4Position")
                        .HasColumnType("smallint");

                    b.Property<string>("Corner4Result")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<short>("Course")
                        .HasColumnType("smallint");

                    b.Property<short>("CourseRaceNumber")
                        .HasColumnType("smallint");

                    b.Property<string>("CourseType")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<short>("DataStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("Distance")
                        .HasColumnType("smallint");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<short>("HorsesCount")
                        .HasColumnType("smallint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Name6Chars")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SubName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("SubjectAge2")
                        .HasColumnType("int");

                    b.Property<int>("SubjectAge3")
                        .HasColumnType("int");

                    b.Property<int>("SubjectAge4")
                        .HasColumnType("int");

                    b.Property<int>("SubjectAge5")
                        .HasColumnType("int");

                    b.Property<int>("SubjectAgeYounger")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<short>("TrackCondition")
                        .HasColumnType("smallint");

                    b.Property<short>("TrackCornerDirection")
                        .HasColumnType("smallint");

                    b.Property<short>("TrackGround")
                        .HasColumnType("smallint");

                    b.Property<short>("TrackOption")
                        .HasColumnType("smallint");

                    b.Property<short>("TrackType")
                        .HasColumnType("smallint");

                    b.Property<short>("TrackWeather")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Name", "Course");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.RaceHorseAnalysisData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("AnalysisVersion")
                        .HasColumnType("smallint unsigned");

                    b.Property<short>("BreakthroughPoint")
                        .HasColumnType("smallint");

                    b.Property<short>("CanceledStallPosition")
                        .HasColumnType("smallint");

                    b.Property<short>("CanceledStallRecoveredPosition")
                        .HasColumnType("smallint");

                    b.Property<short>("CornerPoint")
                        .HasColumnType("smallint");

                    b.Property<short>("DownhillPoint")
                        .HasColumnType("smallint");

                    b.Property<short>("GutsPoint")
                        .HasColumnType("smallint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RaceKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<short>("RunningStyle")
                        .HasColumnType("smallint");

                    b.Property<short>("RunningStyleResult")
                        .HasColumnType("smallint");

                    b.Property<short>("SpeedPoint")
                        .HasColumnType("smallint");

                    b.Property<short>("StallPosition")
                        .HasColumnType("smallint");

                    b.Property<short>("StraightPoint")
                        .HasColumnType("smallint");

                    b.Property<short>("UphillPoint")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("RaceKey", "Key");

                    b.ToTable("RaceHorseAnalysis");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.RaceHorseData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<short>("AbnormalResult")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan>("AfterThirdHalongTime")
                        .HasColumnType("time(6)");

                    b.Property<short>("AfterThirdHalongTimeOrder")
                        .HasColumnType("smallint");

                    b.Property<short>("Age")
                        .HasColumnType("smallint");

                    b.Property<short>("Color")
                        .HasColumnType("smallint");

                    b.Property<short>("Course")
                        .HasColumnType("smallint")
                        .HasColumnName("CourseCode");

                    b.Property<short>("DataStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("FirstCornerOrder")
                        .HasColumnType("smallint");

                    b.Property<short>("FourthCornerOrder")
                        .HasColumnType("smallint");

                    b.Property<short>("FrameNumber")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsBlinkers")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("Mark")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("varchar(72)");

                    b.Property<short>("Number")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds")
                        .HasColumnType("smallint");

                    b.Property<string>("OwnerCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<short>("PlaceOddsMax")
                        .HasColumnType("smallint");

                    b.Property<short>("PlaceOddsMin")
                        .HasColumnType("smallint");

                    b.Property<short>("Popular")
                        .HasColumnType("smallint");

                    b.Property<short>("PreviousRaceDays")
                        .HasColumnType("smallint");

                    b.Property<string>("RaceKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<short>("ResultLength1")
                        .HasColumnType("smallint");

                    b.Property<short>("ResultLength2")
                        .HasColumnType("smallint");

                    b.Property<short>("ResultLength3")
                        .HasColumnType("smallint");

                    b.Property<short>("ResultOrder")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan>("ResultTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("RiderCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("RiderName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<short>("RiderWeight")
                        .HasColumnType("smallint");

                    b.Property<short>("RunningStyle")
                        .HasColumnType("smallint");

                    b.Property<short>("SecondCornerOrder")
                        .HasColumnType("smallint");

                    b.Property<short>("Sex")
                        .HasColumnType("smallint");

                    b.Property<short>("ThirdCornerOrder")
                        .HasColumnType("smallint");

                    b.Property<string>("TrainerCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<string>("UniformFormat")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<byte[]>("UniformFormatData")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("VARBINARY(8000)");

                    b.Property<short>("Weight")
                        .HasColumnType("smallint");

                    b.Property<short>("WeightDiff")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("RaceKey", "Key", "RiderCode", "TrainerCode", "Course");

                    b.ToTable("RaceHorses");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.RefundData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<short>("DataStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("Exacta1Number1")
                        .HasColumnType("smallint");

                    b.Property<short>("Exacta1Number2")
                        .HasColumnType("smallint");

                    b.Property<short>("Exacta1Number3")
                        .HasColumnType("smallint");

                    b.Property<short>("Exacta2Number1")
                        .HasColumnType("smallint");

                    b.Property<short>("Exacta2Number2")
                        .HasColumnType("smallint");

                    b.Property<short>("Exacta2Number3")
                        .HasColumnType("smallint");

                    b.Property<int>("ExactaNumber1Money")
                        .HasColumnType("int");

                    b.Property<int>("ExactaNumber2Money")
                        .HasColumnType("int");

                    b.Property<int>("ExactaNumber3Money")
                        .HasColumnType("int");

                    b.Property<short>("Frame1Number1")
                        .HasColumnType("smallint");

                    b.Property<short>("Frame1Number2")
                        .HasColumnType("smallint");

                    b.Property<short>("Frame1Number3")
                        .HasColumnType("smallint");

                    b.Property<short>("Frame2Number1")
                        .HasColumnType("smallint");

                    b.Property<short>("Frame2Number2")
                        .HasColumnType("smallint");

                    b.Property<short>("Frame2Number3")
                        .HasColumnType("smallint");

                    b.Property<int>("FrameNumber1Money")
                        .HasColumnType("int");

                    b.Property<int>("FrameNumber2Money")
                        .HasColumnType("int");

                    b.Property<int>("FrameNumber3Money")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("PlaceNumber1")
                        .HasColumnType("smallint");

                    b.Property<int>("PlaceNumber1Money")
                        .HasColumnType("int");

                    b.Property<short>("PlaceNumber2")
                        .HasColumnType("smallint");

                    b.Property<int>("PlaceNumber2Money")
                        .HasColumnType("int");

                    b.Property<short>("PlaceNumber3")
                        .HasColumnType("smallint");

                    b.Property<int>("PlaceNumber3Money")
                        .HasColumnType("int");

                    b.Property<short>("PlaceNumber4")
                        .HasColumnType("smallint");

                    b.Property<int>("PlaceNumber4Money")
                        .HasColumnType("int");

                    b.Property<short>("PlaceNumber5")
                        .HasColumnType("smallint");

                    b.Property<int>("PlaceNumber5Money")
                        .HasColumnType("int");

                    b.Property<short>("Quinella1Number1")
                        .HasColumnType("smallint");

                    b.Property<short>("Quinella1Number2")
                        .HasColumnType("smallint");

                    b.Property<short>("Quinella1Number3")
                        .HasColumnType("smallint");

                    b.Property<short>("Quinella2Number1")
                        .HasColumnType("smallint");

                    b.Property<short>("Quinella2Number2")
                        .HasColumnType("smallint");

                    b.Property<short>("Quinella2Number3")
                        .HasColumnType("smallint");

                    b.Property<int>("QuinellaNumber1Money")
                        .HasColumnType("int");

                    b.Property<int>("QuinellaNumber2Money")
                        .HasColumnType("int");

                    b.Property<int>("QuinellaNumber3Money")
                        .HasColumnType("int");

                    b.Property<short>("QuinellaPlace1Number1")
                        .HasColumnType("smallint");

                    b.Property<short>("QuinellaPlace1Number2")
                        .HasColumnType("smallint");

                    b.Property<short>("QuinellaPlace1Number3")
                        .HasColumnType("smallint");

                    b.Property<short>("QuinellaPlace1Number4")
                        .HasColumnType("smallint");

                    b.Property<short>("QuinellaPlace1Number5")
                        .HasColumnType("smallint");

                    b.Property<short>("QuinellaPlace1Number6")
                        .HasColumnType("smallint");

                    b.Property<short>("QuinellaPlace1Number7")
                        .HasColumnType("smallint");

                    b.Property<short>("QuinellaPlace2Number1")
                        .HasColumnType("smallint");

                    b.Property<short>("QuinellaPlace2Number2")
                        .HasColumnType("smallint");

                    b.Property<short>("QuinellaPlace2Number3")
                        .HasColumnType("smallint");

                    b.Property<short>("QuinellaPlace2Number4")
                        .HasColumnType("smallint");

                    b.Property<short>("QuinellaPlace2Number5")
                        .HasColumnType("smallint");

                    b.Property<short>("QuinellaPlace2Number6")
                        .HasColumnType("smallint");

                    b.Property<short>("QuinellaPlace2Number7")
                        .HasColumnType("smallint");

                    b.Property<int>("QuinellaPlaceNumber1Money")
                        .HasColumnType("int");

                    b.Property<int>("QuinellaPlaceNumber2Money")
                        .HasColumnType("int");

                    b.Property<int>("QuinellaPlaceNumber3Money")
                        .HasColumnType("int");

                    b.Property<int>("QuinellaPlaceNumber4Money")
                        .HasColumnType("int");

                    b.Property<int>("QuinellaPlaceNumber5Money")
                        .HasColumnType("int");

                    b.Property<int>("QuinellaPlaceNumber6Money")
                        .HasColumnType("int");

                    b.Property<int>("QuinellaPlaceNumber7Money")
                        .HasColumnType("int");

                    b.Property<string>("RaceKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<short>("SingleNumber1")
                        .HasColumnType("smallint");

                    b.Property<int>("SingleNumber1Money")
                        .HasColumnType("int");

                    b.Property<short>("SingleNumber2")
                        .HasColumnType("smallint");

                    b.Property<int>("SingleNumber2Money")
                        .HasColumnType("int");

                    b.Property<short>("SingleNumber3")
                        .HasColumnType("smallint");

                    b.Property<int>("SingleNumber3Money")
                        .HasColumnType("int");

                    b.Property<short>("Trifecta1Number1")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta1Number2")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta1Number3")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta1Number4")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta1Number5")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta1Number6")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta2Number1")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta2Number2")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta2Number3")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta2Number4")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta2Number5")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta2Number6")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta3Number1")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta3Number2")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta3Number3")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta3Number4")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta3Number5")
                        .HasColumnType("smallint");

                    b.Property<short>("Trifecta3Number6")
                        .HasColumnType("smallint");

                    b.Property<int>("TrifectaNumber1Money")
                        .HasColumnType("int");

                    b.Property<int>("TrifectaNumber2Money")
                        .HasColumnType("int");

                    b.Property<int>("TrifectaNumber3Money")
                        .HasColumnType("int");

                    b.Property<int>("TrifectaNumber4Money")
                        .HasColumnType("int");

                    b.Property<int>("TrifectaNumber5Money")
                        .HasColumnType("int");

                    b.Property<int>("TrifectaNumber6Money")
                        .HasColumnType("int");

                    b.Property<short>("Trio1Number1")
                        .HasColumnType("smallint");

                    b.Property<short>("Trio1Number2")
                        .HasColumnType("smallint");

                    b.Property<short>("Trio1Number3")
                        .HasColumnType("smallint");

                    b.Property<short>("Trio2Number1")
                        .HasColumnType("smallint");

                    b.Property<short>("Trio2Number2")
                        .HasColumnType("smallint");

                    b.Property<short>("Trio2Number3")
                        .HasColumnType("smallint");

                    b.Property<short>("Trio3Number1")
                        .HasColumnType("smallint");

                    b.Property<short>("Trio3Number2")
                        .HasColumnType("smallint");

                    b.Property<short>("Trio3Number3")
                        .HasColumnType("smallint");

                    b.Property<int>("TrioNumber1Money")
                        .HasColumnType("int");

                    b.Property<int>("TrioNumber2Money")
                        .HasColumnType("int");

                    b.Property<int>("TrioNumber3Money")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceKey");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.SingleOddsTimeline", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<short>("DataStatus")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("Odds1")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds10")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds11")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds12")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds13")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds14")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds15")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds16")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds17")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds18")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds19")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds2")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds20")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds21")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds22")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds23")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds24")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds25")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds26")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds27")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds28")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds3")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds4")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds5")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds6")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds7")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds8")
                        .HasColumnType("smallint");

                    b.Property<short>("Odds9")
                        .HasColumnType("smallint");

                    b.Property<string>("RaceKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RaceKey");

                    b.ToTable("SingleOddsTimelines");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.SystemData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SystemData");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.TrainingData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<short>("Center")
                        .HasColumnType("smallint");

                    b.Property<short>("DataStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("FirstLapTime")
                        .HasColumnType("smallint");

                    b.Property<short>("FourthLapTime")
                        .HasColumnType("smallint");

                    b.Property<string>("HorseKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("SecondLapTime")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("ThirdLapTime")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("HorseKey");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.TrifectaOddsData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<short>("DataStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("HorseNumber1")
                        .HasColumnType("smallint");

                    b.Property<short>("HorseNumber2")
                        .HasColumnType("smallint");

                    b.Property<short>("HorseNumber3")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("Odds")
                        .HasColumnType("smallint");

                    b.Property<string>("RaceKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RaceKey");

                    b.ToTable("TrifectaOdds");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.TrioOddsData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<short>("DataStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("HorseNumber1")
                        .HasColumnType("smallint");

                    b.Property<short>("HorseNumber2")
                        .HasColumnType("smallint");

                    b.Property<short>("HorseNumber3")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("Odds")
                        .HasColumnType("smallint");

                    b.Property<string>("RaceKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RaceKey");

                    b.ToTable("TrioOdds");
                });

            modelBuilder.Entity("KmyKeiba.Data.Db.WoodtipTrainingData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<short>("Center")
                        .HasColumnType("smallint");

                    b.Property<short>("Course")
                        .HasColumnType("smallint");

                    b.Property<short>("DataStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("Direction")
                        .HasColumnType("smallint");

                    b.Property<string>("HorseKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<short>("Lap10Time")
                        .HasColumnType("smallint");

                    b.Property<short>("Lap1Time")
                        .HasColumnType("smallint");

                    b.Property<short>("Lap2Time")
                        .HasColumnType("smallint");

                    b.Property<short>("Lap3Time")
                        .HasColumnType("smallint");

                    b.Property<short>("Lap4Time")
                        .HasColumnType("smallint");

                    b.Property<short>("Lap5Time")
                        .HasColumnType("smallint");

                    b.Property<short>("Lap6Time")
                        .HasColumnType("smallint");

                    b.Property<short>("Lap7Time")
                        .HasColumnType("smallint");

                    b.Property<short>("Lap8Time")
                        .HasColumnType("smallint");

                    b.Property<short>("Lap9Time")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("HorseKey");

                    b.ToTable("WoodtipTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
